version: '6.7'

services:
  backend:
    # depends_on:
    build: ./backend
    restart: unless-stopped
    # env_file: ./.env
    ports:
      - "3500:3500"

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000" 
  nginx:
        depends_on:
          - backend
          - frontend
        restart: always
        build:
            context: ./nginx
        ports:
            - "8080:8080"
volumes: 
  db:

networks:
  backend:
  frontend: